services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    volumes:
      - .:/home/code
    ports:
      - "8000:8000"
    command: chainlit run src/app.py -w
    # command: sleep infinity

  ollama:
    image: ollama/ollama:latest  
    ports:
      - "11434:11434"  
    restart: unless-stopped

  neo4j:
    image: neo4j:5.16.0
    restart: unless-stopped
    volumes:
      - ./data/neo4j:/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]